<div style="width: 100%; clear: both;">
    <div style="float: left; width: 50%;">
        <img src="../figs/uoc_masterbrand_3linies_positiu.png", align="left">
    </div>
    <div style="float: right; width: 50%;">
        <p style="margin: 0; padding-top: 22px; text-align:right;">M2.855 · Models avançats de mineria de dades</p>
        <p style="margin: 0; text-align:right;">Màster universitari en Ciència de dades (<i>Data science</i>)</p>
        <p style="margin: 0; text-align:right; padding-button: 100px;">Estudis d'Informàtica, Multimèdia i Telecomunicació</p>
    </div>
</div>
<div style="width:100%;">&nbsp;</div>

# Exemple de classificació mitjançant SVM

## 1. Càrrega de les dades

En primer lloc, carregarem el conjunt de dades IRIS dataset (Més informació a https://archive.ics.uci.edu/ml/datasets/iris). Aquest es pot descarregar d'Internet o es pot carregar directament de la llibreria `scikit-learn`, que incorpora un conjunt de datasets molt coneguts i emprats per a mineria de dades i machine learning.

In [1]:
from sklearn import datasets

# import some data to play with
iris = datasets.load_iris()
X = iris.data
y = iris.target
class_names = iris.target_names

## 2. Preparació del conjunt d'entrenament i test

Generem els conjunts d'entrenament i tests mitjançant la llibreria `train_test_split`.

In [2]:
from sklearn.model_selection import train_test_split

# Split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

## 3. Creació i entrenament del model

Les línies de codi següents creen i entrenen un model basat en SVM.

In [3]:
from sklearn import svm

# Run classifier
classifier = svm.SVC(kernel='linear', C=0.1)
classifier.fit(X_train, y_train)

SVC(C=0.1, kernel='linear')

## 4. Validació del model

En primer lloc, comprovarem la precisió sobre el conjunt de dades de test. I, tot seguit, crearem la matriu de confusió associada.

In [4]:
from sklearn.metrics import confusion_matrix
import numpy as np

# Prediction on test data
y_pred = classifier.predict(X_test)

# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, y_pred)
np.set_printoptions(precision=2)

print(cnf_matrix)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
